import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as XLSX from 'xlsx'
import {
  parseCsv,
  parseXlsxRows,
  rowsToBulkAgents,
  hasSpreadsheetFormulaRisk,
  RosterSheetTooLargeError,
  MAX_ROSTER_ROWS,
  XLSX_SHEET_ROW_LIMIT,
} from './roster-import'

// Frozen copies of the real deliverables (the live ones are regenerated by
// scripts/build-onboarding-roster.py and may change content over time).
const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), '__fixtures__')

// Build an in-memory xlsx from an array-of-arrays, for synthetic cases.
function buildXlsx(aoa: (string[] | undefined)[]): Uint8Array {
  const ws = XLSX.utils.aoa_to_sheet(aoa.map(row => row ?? []))
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Sheet1')
  return new Uint8Array(XLSX.write(wb, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer)
}

describe('parseCsv', () => {
  it('parses simple rows', () => {
    expect(parseCsv('a,b,c\nd,e,f')).toEqual([
      ['a', 'b', 'c'],
      ['d', 'e', 'f'],
    ])
  })

  it('handles quoted commas, escaped quotes, and CRLF', () => {
    const text = '"Smith, Jane","She said ""hi""",x\r\n1,2,3\r\n'
    expect(parseCsv(text)).toEqual([
      ['Smith, Jane', 'She said "hi"', 'x'],
      ['1', '2', '3'],
    ])
  })

  it('preserves interior blank rows so indices track source line numbers', () => {
    expect(parseCsv('a,b\n,\n\n c,d\n')).toEqual([
      ['a', 'b'],
      ['', ''],
      [''],
      [' c', 'd'],
    ])
  })
})

describe('hasSpreadsheetFormulaRisk', () => {
  it('flags formula-like values', () => {
    expect(hasSpreadsheetFormulaRisk('=SUM(A1)', 'Notes')).toBe(true)
    expect(hasSpreadsheetFormulaRisk('@cmd', 'First Name')).toBe(true)
    expect(hasSpreadsheetFormulaRisk('+1=1', 'Notes')).toBe(true)
  })

  it('allows leading + in phone-like columns only', () => {
    expect(hasSpreadsheetFormulaRisk('+1 416 555 0100', 'Phone')).toBe(false)
    expect(hasSpreadsheetFormulaRisk('+1 416 555 0100', 'Notes')).toBe(true)
  })
})

describe('rowsToBulkAgents', () => {
  const header = ['First Name', 'Last Name', 'Email', 'Phone']
  const agentRow = ['Jane', 'Realtor', 'jane@example.com', '416 555 0100']

  it('maps a simple roster', () => {
    const result = rowsToBulkAgents([header, agentRow])
    expect(result.error).toBeUndefined()
    expect(result.agents).toEqual([
      {
        firstName: 'Jane',
        lastName: 'Realtor',
        email: 'jane@example.com',
        phone: '416 555 0100',
        recoNumber: undefined,
        addressStreet: undefined,
        addressCity: undefined,
        addressProvince: undefined,
        addressPostalCode: undefined,
        sourceRow: 2,
      },
    ])
  })

  it('finds a header row buried under 11 banner rows (branded roster layout)', () => {
    const banner = Array.from({ length: 11 }, (_, i) => [`Banner line ${i}`])
    const result = rowsToBulkAgents([...banner, header, agentRow])
    expect(result.error).toBeUndefined()
    expect(result.agents).toHaveLength(1)
    expect(result.agents[0].firstName).toBe('Jane')
    expect(result.agents[0].sourceRow).toBe(13)
  })

  it('gives up when no header row exists in the first 25 rows', () => {
    const banner = Array.from({ length: 30 }, (_, i) => [`Banner line ${i}`])
    const result = rowsToBulkAgents([...banner, header, agentRow])
    expect(result.error).toMatch(/header row/i)
  })

  it('ignores unknown columns like #, Status, Notes', () => {
    const result = rowsToBulkAgents([
      ['#', 'First Name', 'Last Name', 'Email', 'Status', 'Notes'],
      ['1', 'Jane', 'Realtor', 'jane@example.com', 'Active', 'top producer'],
    ])
    expect(result.error).toBeUndefined()
    expect(result.agents[0]).toMatchObject({
      firstName: 'Jane',
      lastName: 'Realtor',
      email: 'jane@example.com',
    })
  })

  it('drops rows whose mapped columns are all empty (pre-styled roster rows)', () => {
    const result = rowsToBulkAgents([
      ['#', 'First Name', 'Last Name', 'Email', 'Status'],
      ['1', 'Jane', 'Realtor', 'jane@example.com', 'Active'],
      ['2', '', '', '', 'Active'],
      ['3', '', '', '', 'Active'],
    ])
    expect(result.error).toBeUndefined()
    expect(result.agents).toHaveLength(1)
  })

  it('keeps accurate source rows across blank and decoration rows', () => {
    const result = rowsToBulkAgents([
      header,
      agentRow, // row 2
      ['', '', '', ''], // row 3 blank
      ['', '', '', ''], // row 4 blank
      ['John', 'Late', '', ''], // row 5
    ])
    expect(result.error).toBeUndefined()
    expect(result.agents.map(a => a.sourceRow)).toEqual([2, 5])
  })

  it('does not let an "Email Address" header satisfy the street-address column', () => {
    const result = rowsToBulkAgents([
      ['First Name', 'Last Name', 'Email Address', 'Street Address'],
      ['Jane', 'Realtor', 'jane@example.com', '123 Main St'],
    ])
    expect(result.agents[0].email).toBe('jane@example.com')
    expect(result.agents[0].addressStreet).toBe('123 Main St')
  })

  it('maps "Mailing Address" to street address, never to email', () => {
    const result = rowsToBulkAgents([
      ['First Name', 'Last Name', 'Mailing Address', 'Email'],
      ['Jane', 'Realtor', '123 Main St', 'jane@example.com'],
    ])
    expect(result.agents[0].email).toBe('jane@example.com')
    expect(result.agents[0].addressStreet).toBe('123 Main St')
  })

  it('rejects formula-like cell values with the offending row number', () => {
    const result = rowsToBulkAgents([
      header,
      agentRow,
      ['=HYPERLINK("http://evil")', 'Realtor', 'evil@example.com', ''],
    ])
    expect(result.error).toMatch(/Row 3: spreadsheet formula-like/)
    expect(result.agents).toHaveLength(0)
  })

  it('enforces the row cap on actual agent rows', () => {
    const rows = [header, ...Array.from({ length: MAX_ROSTER_ROWS + 1 }, (_, i) => [`A${i}`, `B${i}`, `a${i}@x.com`, ''])]
    const result = rowsToBulkAgents(rows)
    expect(result.error).toMatch(/Maximum 200 agents/)
  })

  it('errors when there are no data rows', () => {
    expect(rowsToBulkAgents([header]).error).toMatch(/no agent rows/i)
  })
})

describe('parseXlsxRows on synthetic workbooks', () => {
  it('keeps agents separated by large blank gaps, with accurate source rows', () => {
    const aoa: (string[] | undefined)[] = [['First Name', 'Last Name', 'Email'], ['Jane', 'One', '']]
    aoa[499] = ['John', 'Two', ''] // physical row 500
    const result = rowsToBulkAgents(parseXlsxRows(buildXlsx(aoa)))
    expect(result.error).toBeUndefined()
    expect(result.agents.map(a => [a.firstName, a.sourceRow])).toEqual([
      ['Jane', 2],
      ['John', 500],
    ])
  })

  it('rejects sheets whose used range exceeds the row limit instead of truncating', () => {
    const aoa: (string[] | undefined)[] = [['First Name', 'Last Name', 'Email']]
    aoa[XLSX_SHEET_ROW_LIMIT + 99] = ['Far', 'Away', '']
    expect(() => parseXlsxRows(buildXlsx(aoa))).toThrow(RosterSheetTooLargeError)
  })

  it('degrades gracefully on non-spreadsheet bytes (fails header detection, no crash)', () => {
    // SheetJS falls back to text parsing for unrecognized bytes; the junk
    // rows then fail header detection downstream instead of crashing.
    const rows = parseXlsxRows(new Uint8Array([0, 1, 2, 3]))
    expect(rowsToBulkAgents(rows).error).toMatch(/header row/i)
  })
})

describe('parseXlsxRows on frozen fixtures of the real deliverables', () => {
  it('imports all 47 agents from the branded onboarding roster (header on row 12)', () => {
    const bytes = readFileSync(join(FIXTURES, 'onboarding-roster.xlsx'))
    const rows = parseXlsxRows(bytes)
    const result = rowsToBulkAgents(rows)

    expect(result.error).toBeUndefined()
    expect(result.agents).toHaveLength(47)
    expect(result.agents[0]).toMatchObject({ firstName: 'Marc', lastName: 'Beaudette', sourceRow: 13 })
    expect(result.agents[0].phone).toBe('705-542-1016')
    expect(result.agents[result.agents.length - 1]).toMatchObject({ firstName: 'Andrea', lastName: 'Zavitz', sourceRow: 59 })
    const withEmail = result.agents.filter(agent => agent.email)
    expect(withEmail.map(agent => agent.email).sort()).toEqual([
      'bud.jones@century21.ca',
      'james.caicco@century21.ca',
    ])
    // The "How to Use" sheet must not bleed into the parsed rows
    expect(rows.flat().join(' ')).not.toMatch(/How to Use|What this is/i)
  })

  it('imports the download template with addresses mapped correctly', () => {
    const bytes = readFileSync(join(FIXTURES, 'import-template.xlsx'))
    const result = rowsToBulkAgents(parseXlsxRows(bytes))

    expect(result.error).toBeUndefined()
    expect(result.agents).toHaveLength(2)
    expect(result.agents[0]).toMatchObject({
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane.smith@example.com',
      addressStreet: '123 Main St',
      addressCity: 'Sault Ste. Marie',
      addressProvince: 'ON',
      addressPostalCode: 'P6A 1A1',
    })
    expect(result.agents[1]).toMatchObject({ firstName: 'John', lastName: 'Doe' })
  })
})

describe('live deliverables stay importable (structural checks only)', () => {
  // The repo-root roster and the public template are living files that get
  // regenerated; assert they still parse, not their exact contents.
  it.each([
    ['Firm-Funds-Agent-Onboarding-Roster.xlsx', join(process.cwd(), 'Firm-Funds-Agent-Onboarding-Roster.xlsx')],
    ['public/firm-funds-agent-import-template.xlsx', join(process.cwd(), 'public', 'firm-funds-agent-import-template.xlsx')],
  ])('%s parses with a detectable header and at least one agent', (_name, path) => {
    const result = rowsToBulkAgents(parseXlsxRows(readFileSync(path)))
    expect(result.error).toBeUndefined()
    expect(result.agents.length).toBeGreaterThan(0)
  })
})
