-- Migration 062: protect the agent ledger from cascade-delete wipe
--
-- AUDIT FINDING #15 (HIGH): agent_transactions.agent_id, agent_invoices.agent_id,
-- and remediation_deals.agent_id are all ON DELETE CASCADE. The trigger
-- prevent_agent_delete_with_deals (migration 034) only checks for active
-- deals. If an agent has no current deals but has historical ledger entries
-- (credits, adjustments, balance_deductions), they can be deleted and the
-- entire financial history evaporates — FINTRAC/CRA auditability destroyed.
--
-- Fix part 1: change CASCADE → RESTRICT on the ledger-bearing FKs so a
-- delete attempt errors instead of silently destroying history.
--
-- Fix part 2: extend prevent_agent_delete_with_deals to also block when
-- agent_transactions or agent_invoices reference the agent. The trigger
-- becomes the canonical guard; the RESTRICT FKs are belt-and-suspenders.

-- ---------------------------------------------------------------------------
-- Part 1: CASCADE → RESTRICT on ledger FKs.
-- The original FK constraint names follow Postgres autogenerated convention.
-- We DROP IF EXISTS the autogen names and recreate with explicit name + RESTRICT.
-- ---------------------------------------------------------------------------

ALTER TABLE agent_transactions
  DROP CONSTRAINT IF EXISTS agent_transactions_agent_id_fkey;
ALTER TABLE agent_transactions
  ADD CONSTRAINT agent_transactions_agent_id_fkey
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE RESTRICT;

ALTER TABLE agent_invoices
  DROP CONSTRAINT IF EXISTS agent_invoices_agent_id_fkey;
ALTER TABLE agent_invoices
  ADD CONSTRAINT agent_invoices_agent_id_fkey
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE RESTRICT;

-- remediation_deals.agent_id is already RESTRICT from migration 049, but the
-- DROP IF EXISTS + ADD pattern is idempotent and harmless if so.
ALTER TABLE remediation_deals
  DROP CONSTRAINT IF EXISTS remediation_deals_agent_id_fkey;
ALTER TABLE remediation_deals
  ADD CONSTRAINT remediation_deals_agent_id_fkey
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE RESTRICT;

-- ---------------------------------------------------------------------------
-- Part 2: extend the agent-delete guard trigger.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION prevent_agent_delete_with_history() RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_deal_count int;
  v_txn_count int;
  v_invoice_count int;
BEGIN
  SELECT COUNT(*) INTO v_deal_count
    FROM deals WHERE agent_id = OLD.id;

  IF v_deal_count > 0 THEN
    RAISE EXCEPTION
      'Cannot DELETE agent %: % deals reference this agent. Soft-delete (set deleted_at) instead.',
      OLD.id, v_deal_count
      USING ERRCODE = 'restrict_violation';
  END IF;

  SELECT COUNT(*) INTO v_txn_count
    FROM agent_transactions WHERE agent_id = OLD.id;

  IF v_txn_count > 0 THEN
    RAISE EXCEPTION
      'Cannot DELETE agent %: % agent_transactions reference this agent. Ledger history must be preserved for audit. Soft-delete instead.',
      OLD.id, v_txn_count
      USING ERRCODE = 'restrict_violation';
  END IF;

  SELECT COUNT(*) INTO v_invoice_count
    FROM agent_invoices WHERE agent_id = OLD.id;

  IF v_invoice_count > 0 THEN
    RAISE EXCEPTION
      'Cannot DELETE agent %: % agent_invoices reference this agent. Soft-delete instead.',
      OLD.id, v_invoice_count
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN OLD;
END;
$$;

-- Drop the old narrower trigger (migration 034) and install the wider one.
DROP TRIGGER IF EXISTS prevent_agent_delete_trigger ON agents;
DROP TRIGGER IF EXISTS prevent_agent_delete_with_deals_trigger ON agents;
DROP TRIGGER IF EXISTS prevent_agent_delete_with_history_trigger ON agents;

CREATE TRIGGER prevent_agent_delete_with_history_trigger
  BEFORE DELETE ON agents
  FOR EACH ROW EXECUTE FUNCTION prevent_agent_delete_with_history();

COMMENT ON FUNCTION prevent_agent_delete_with_history() IS
  'Blocks DELETE on agents that have deals, agent_transactions, or agent_invoices history. See migration 062.';
