-- Migration 096: Brokerage logo tagline flag
--
-- Added to support the brokerage logo generator (lib/brokerage-logo-generator.ts),
-- which produces SVGs with "Powered by Firm Funds" baked into the image. When
-- this flag is TRUE, templates that render the brokerage logo should NOT add a
-- separate Firm Funds wordmark beside it (which would be a duplicate).
--
-- TRUE  = logo_url contains the "Powered by Firm Funds" tagline (generated logos)
-- FALSE = logo_url is a bare brokerage logo (uploaded custom logos) and templates
--         should render the separate FF endorsement next to it (existing behavior)

ALTER TABLE brokerages
  ADD COLUMN IF NOT EXISTS logo_includes_tagline boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN brokerages.logo_includes_tagline IS
  'TRUE when logo_url contains the "Powered by Firm Funds" tagline baked in (generated by lib/brokerage-logo-generator.ts). Templates use this to avoid double-rendering the FF wordmark next to the logo.';
