import type { HelpArticle } from '../../types'
import HelpCallout from '@/components/help/HelpCallout'

function Body() {
  return (
    <div className="space-y-4 text-sm leading-relaxed text-foreground/90">
      <p>
        An IDP, or Irrevocable Direction to Pay, is a short legal document
        signed by the agent and the brokerage that redirects a specific
        upcoming commission payment to Firm Funds. A Remediation IDP is the
        version we use when a previously advanced deal fails to close and the
        agent elects to cure the unpaid balance by assigning a future
        commission instead of repaying in cash.
      </p>

      <h2 className="text-lg font-semibold text-foreground mt-6">
        When a Remediation IDP gets used
      </h2>
      <p>
        After a deal moves to <code>failed_to_close</code>, the agent has 15
        days to elect a cure path. There are two options. The first is cash
        repayment of the outstanding balance. The second is commission
        assignment, which is where the Remediation IDP comes in. The agent
        names a specific upcoming commission of theirs at the same brokerage,
        and that commission gets redirected to Firm Funds when it pays out.
      </p>
      <p>
        This is the option created under{' '}
        <strong className="text-primary">Article 5.5(b)</strong> of the
        Commission Purchase Agreement. The agent and brokerage both sign the
        IDP. Once signed, the named commission is committed; the brokerage is
        on notice that when those funds land in their trust account, the
        directed amount must be remitted to Firm Funds before any payout to
        the agent.
      </p>

      <h2 className="text-lg font-semibold text-foreground mt-6">
        What is on the document
      </h2>
      <p>
        A Remediation IDP is one page. It names:
      </p>
      <ul className="list-disc pl-6 space-y-1.5">
        <li>The agent and the brokerage.</li>
        <li>
          The specific upcoming deal whose commission is being redirected
          (property address, expected closing date, gross commission).
        </li>
        <li>
          The original failed deal whose balance this is curing, and the
          dollar amount Firm Funds is directed to receive (principal plus
          accrued interest as of signing).
        </li>
        <li>
          The brokerage&apos;s acknowledgement that the direction is
          irrevocable until the directed amount is paid in full.
        </li>
      </ul>
      <p>
        Signing is done by DocuSign. Once both parties have signed, the
        executed PDF is stored on the file and a copy is sent to each party.
      </p>

      <HelpCallout
        variant="note"
        title="What makes the direction irrevocable"
      >
        <p>
          Once the IDP is executed, neither the agent nor the brokerage can
          unilaterally cancel it. The agent cannot route the named commission
          to themselves and then settle separately, and the brokerage cannot
          accept a verbal request from the agent to ignore the direction.
          Cancellation only happens if Firm Funds expressly releases the IDP
          in writing, which we do once the directed amount has been paid in
          full or another remediation path has resolved the underlying
          balance.
        </p>
      </HelpCallout>

      <h2 className="text-lg font-semibold text-foreground mt-6">
        What happens at the underlying closing
      </h2>
      <p>
        When the named commission lands in the brokerage&apos;s trust account
        at closing, the brokerage remits the directed amount to Firm Funds.
        Any remainder of that commission, after the directed amount and the
        brokerage&apos;s normal split, is paid to the agent as usual. We
        credit the directed amount to the failed deal&apos;s outstanding
        balance and post it to the agent&apos;s ledger. If the directed
        amount fully clears the balance, the failed deal moves to{' '}
        <code>cured</code>.
      </p>

      <h2 className="text-lg font-semibold text-foreground mt-6">
        Where this lives in the code and the contract
      </h2>
      <p>
        The document is generated by <code>generateRemediationIdpDocx</code>
        {' '}in <code>lib/contract-docx.ts</code>. The signing and remittance
        flow is in <code>lib/actions/remediation-actions.ts</code>. The
        contractual basis is Article 5.5(b) of the Commission Purchase
        Agreement; the IDP itself is a stand-alone Schedule referenced by
        that article.
      </p>
    </div>
  )
}

const article: HelpArticle = {
  meta: {
    slug: 'what-a-remediation-idp-is',
    title: 'What a Remediation IDP is',
    summary: 'Plain-language guide to the irrevocable direction to pay we use after a failed deal.',
    role: 'shared',
    category: 'money-and-policy',
    order: 40,
    updatedAt: '2026-05-29',
  },
  Body,
}

export default article
